name: 0. Initialize Release

run-name: ${{ github.ref_name }} Setup Release

on:
  push:
    tags:
      - '[0-9]*'

permissions:
  contents: write

jobs:
  init-release:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸš€ Create Release
        uses: softprops/action-gh-release@v2
        with:
          # âœ… åªæœ‰è¿™é‡Œå¼€å¯æ—¥å¿—ç”Ÿæˆ
          generate_release_notes: true
          # è®¾ä¸º draft å¯ä»¥é¿å…ç”¨æˆ·åœ¨æ–‡ä»¶æ²¡ä¼ å®Œæ—¶ä¸‹è½½ï¼Œç¡®è®¤æ— è¯¯åæ‰‹åŠ¨å‘å¸ƒï¼ˆå¯é€‰ï¼‰
          # draft: true
          # prerelease: false
